# Generated by Django 5.0.7 on 2024-07-29 15:00

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fca_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FCA Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADVISER", "Adviser"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Administrator"),
                    ("SUPER_ADMIN", "Super Administrator"),
                ],
                default="ADVISER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
