# Generated by Django 5.0.7 on 2024-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agency_number",
            field=models.CharField(
                blank=True,
                help_text="Уникальный номер агентства/менеджера",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parent_agency_id",
            field=models.CharField(
                blank=True,
                help_text="Номер родительского агентства",
                max_length=50,
                null=True,
            ),
        ),
    ]
