# Generated by Django 4.2.25 on 2025-10-02 16:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("contact_details", models.TextField(blank=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("employment_status", models.CharField(blank=True, max_length=100)),
                ("risk_category", models.CharField(blank=True, max_length=50)),
                ("corporate_client_flag", models.BooleanField(default=False)),
                ("client_group_id", models.CharField(blank=True, max_length=100)),
                (
                    "client_lifetime_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "client_satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("gdpr_consent_status", models.BooleanField(default=False)),
                ("marketing_consent_flag", models.BooleanField(default=False)),
                ("marketing_source", models.CharField(blank=True, max_length=100)),
                ("income_details", models.JSONField(blank=True, null=True)),
                ("credit_score", models.CharField(blank=True, max_length=50)),
                ("mortgage_history", models.TextField(blank=True)),
                ("client_complaint_flag", models.BooleanField(default=False)),
                ("client_complaint_details", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Adviser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adviser_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("fca_reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True, help_text="e.g., Experienced, CAS", max_length=50
                    ),
                ),
                ("club", models.CharField(blank=True, max_length=100)),
                ("agency_number", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("contact_details", models.TextField(blank=True)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("hierarchy_level", models.IntegerField(blank=True, null=True)),
                (
                    "role_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Lead, Junior, Override",
                        max_length=50,
                    ),
                ),
                ("active_flag", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("aml_check_status", models.BooleanField(default=False)),
                (
                    "default_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Default percentage of the net commission the adviser earns.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADVISER", "Adviser"),
                            ("MANAGER", "Manager"),
                            ("FINANCE", "Finance Manager"),
                            ("COMPLIANCE", "Compliance Officer"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="ADVISER",
                        max_length=20,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="core.adviser",
                    ),
                ),
            ],
        ),
    ]
