# Generated by Django 4.2.25 on 2025-10-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adviser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала работы")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Процент вознаграждения консультанта от комиссии",
                        max_digits=5,
                        verbose_name="Процент вознаграждения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активен"),
                            ("ON_LEAVE", "В отпуске"),
                            ("TERMINATED", "Уволен"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADVISER", "Консультант"),
                            ("MANAGER", "Менеджер"),
                            ("TRAINEE", "Стажер"),
                        ],
                        default="ADVISER",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "parent_adviser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="advisers.adviser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультант",
                "verbose_name_plural": "Консультанты",
            },
        ),
    ]
