# Generated by Django 4.2.25 on 2025-10-02 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advisers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adviser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adviser_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
