# Generated by Django 5.0.7 on 2024-08-02 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.AddField(
            model_name="client",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="Default Name", max_length=200, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
