# Generated by Django 5.0.7 on 2024-07-29 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название отчета"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("commission_summary", "Сводка по комиссиям"),
                            ("performance_analysis", "Анализ производительности"),
                            ("forecast", "Прогноз"),
                        ],
                        max_length=50,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные отчета")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем сгенерирован",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
                "ordering": ["-created_at"],
            },
        ),
    ]

