# Generated by Django 5.0.7 on 2024-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("IN_PROGRESS", "В обработке"),
                    ("SUCCESS", "Успешно"),
                    ("FAILURE", "Ошибка"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус генерации",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID задачи Celery"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Данные отчета"
            ),
        ),
    ]

