# Generated by Django 5.0.7 on 2024-08-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mortgage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Удаление старых полей ---
        migrations.RemoveField(model_name="mortgagecase", name="borrower"),
        migrations.RemoveField(model_name="mortgagecase", name="closing_date"),
        migrations.RemoveField(model_name="mortgagecase", name="loan_officer"),
        migrations.RemoveField(model_name="mortgagecase", name="loan_term"),
        migrations.RemoveField(model_name="mortgagecase", name="property_value"),
        migrations.RemoveField(model_name="commission", name="base_commission_amount"),
        migrations.RemoveField(model_name="commission", name="base_commission_rate"),
        migrations.RemoveField(model_name="commission", name="payout_date"),
        migrations.RemoveField(model_name="commission", name="payout_status"),
        migrations.RemoveField(model_name="commission", name="total_amount"),

        # --- Создание новых моделей ---
        migrations.CreateModel(
            name="Lender",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lender_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contact_details', models.TextField(blank=True)),
                ('fca_reference_number', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BrokerFee",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AIP', 'Agreement in Principle'), ('OFFER', 'Mortgage Offer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_invoiced', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('mortgage_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_fees', to='mortgage.mortgagecase')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageIngestionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MortgageBonus',
            fields=[
                ('commissionmodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.commissionmodifier')),
            ],
            bases=('mortgage.commissionmodifier',),
        ),
        migrations.CreateModel(
            name='MortgageClawback',
            fields=[
                ('commissionmodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.commissionmodifier')),
            ],
            bases=('mortgage.commissionmodifier',),
        ),
        migrations.CreateModel(
            name='MortgageOverride',
            fields=[
                ('commissionmodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.commissionmodifier')),
            ],
            bases=('mortgage.commissionmodifier',),
        ),
        migrations.CreateModel(
            name='MortgageReferralFee',
            fields=[
                ('commissionmodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.commissionmodifier')),
            ],
            bases=('mortgage.commissionmodifier',),
        ),
        migrations.CreateModel(
            name='MortgageRetention',
            fields=[
                ('commissionmodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.commissionmodifier')),
            ],
            bases=('mortgage.commissionmodifier',),
        ),

        # --- Обновление существующих моделей ---
        migrations.AddField(model_name='mortgagecase', name='adviser', field=models.ForeignKey(limit_choices_to={'role': 'ADVISER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_cases', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='mortgagecase', name='client', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_cases', to='clients.client')),
        migrations.AlterField(model_name='mortgagecase', name='lender', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_cases', to='mortgage.lender')),
        migrations.AddField(model_name='mortgagecase', name='application_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='automated_notification_status', field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='mortgagecase', name='case_document_links', field=models.JSONField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='client_source', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='mortgagecase', name='completion_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='cross_sell_opportunity', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='mortgagecase', name='deposit_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
        migrations.AddField(model_name='mortgagecase', name='digital_signature_status', field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='mortgagecase', name='expiry_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='fee_structure', field=models.JSONField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='integration_id', field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name='mortgagecase', name='mortgage_expiry_reminder_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='mortgage_expiry_reminder_sent', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='mortgagecase', name='mortgage_purpose', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='mortgagecase', name='mortgage_type', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='mortgagecase', name='offer_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='product_code', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='mortgagecase', name='term_months', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='mortgagecase', name='upsell_opportunity', field=models.BooleanField(default=False)),
        migrations.AlterField(model_name='mortgagecase', name='status', field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('completed', 'Завершен'), ('withdrawn', 'Отозван'), ('failed', 'Ошибка'), ('pending', 'В ожидании'), ('cancelled', 'Отменен'), ('on_hold', 'Приостановлен'), ('awaiting_documents', 'Ожидание документов'), ('documents_received', 'Документы получены'), ('underwriting', 'На рассмотрении'), ('offer_made', 'Предложение ��делано'), ('offer_accepted', 'Предложение принято'), ('offer_rejected', 'Предложение отклонено'), ('completion_arranged', 'Завершение запланировано'), ('funds_disbursed', 'Средства выплачены'), ('mortgage_registered', 'Ипотека зарегистрирована'), ('refinance_arranged', 'Рефинансирование запланировано'), ('early_repayment', 'Досрочное погашение'), ('default', 'По умолчанию'), ('denied', 'Отказан'), ('closed', 'Закрыт')], default='new', max_length=30, verbose_name='Статус')),
        migrations.AlterField(
            model_name="mortgagecase",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("residential", "Жилая недвижимость"),
                    ("buy_to_let", "Покупка для сдачи в аренду"),
                    ("remortgage", "Рефинансирование"),
                    ("other", "Другое"),
                ],
                default="residential",
                max_length=20,
                verbose_name="Тип продукта",
            ),
        ),

        migrations.AddField(model_name='commission', name='adviser_fee_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='commission', name='adviser_fee_percentage', field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name='commission', name='automated_notification_status', field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='commission', name='commission_adjustment_reason', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commission', name='commission_due_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='commission', name='commission_invoice_number', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='commission', name='currency_code', field=models.CharField(default='GBP', max_length=3)),
        migrations.AddField(model_name='commission', name='date_paid_to_adviser', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='commission', name='date_received', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='commission', name='forecasted_commission', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='commission', name='gross_commission', field=models.DecimalField(decimal_places=2, max_digits=10)),
        migrations.AddField(model_name='commission', name='integration_id', field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name='commission', name='net_commission', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='commission', name='payment_attachment_links', field=models.JSONField(blank=True, null=True)),
        migrations.AddField(model_name='commission', name='payment_method', field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name='commission', name='payment_reference', field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name='commission', name='payment_status', field=models.CharField(default='Pending', max_length=50)),
        migrations.AddField(model_name='commission', name='vat_included', field=models.BooleanField(default=False)),
    ]
