# Generated by Django 5.0.7 on 2024-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgagecase",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("residential", "Жилая недвижимость"),
                    ("buy_to_let", "Покупка для сдачи в аренду"),
                    ("remortgage", "Рефинансирование"),
                    ("other", "Другое"),
                ],
                default="residential",
                max_length=20,
                verbose_name="Тип продукта",
            ),
        ),
    ]

