# Generated by Django 5.0.7 on 2024-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgage", "0002_auto_20240801_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgagecase",
            name="case_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
